### ISSUE TITLE
License & desktop file

### ISSUE THREAD

**Issue by otaj** [darthoctopus/pyneapple#3]
Hi,

what is the license for you project? I really like pyneapple so I'm planning to package it for AUR, however, AUR requires some sort of license.

And BTW, what is the ETA for your own icon? I can probably package it with the one from nwhitehead (that's what I'm using on my system anyway), however I think it would be better if you had your own.

Thanks,
Ota

**Comment by darthoctopus** [comment]
Hello!

I also use Arch!  I haven't had the time to put it on the AUR lately, and this will likely persist until the end of June (qualifying exam for a graduate program). Consider this also to be the ETA for an icon.

For now it's available on PyPI (i.e. via `pip`), released under GPLv3 (and it says so in setup.py). However you're welcome to put it on the AUR too.

I've created a license file (69c45dd) if it helps.

**Comment by otaj** [comment]
Hi! Sorry, that it took so long, I just didn't have time to get to it. However, package is on AUR! https://aur.archlinux.org/packages/python-pyneapple-git/
